repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
          - id: black
            args: ['--target-version', 'py311']
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
          - id: isort
    - repo: https://github.com/pycqa/pylint
      rev: v3.0.0a6
      hooks:
          - id: pylint
            args:
                [
                    '--rcfile=pyproject.toml',
                    '--disable=C0114',
                    '--disable=R0903',
                ]
            additional_dependencies:
                [python-dotenv, fastapi, uvicorn, pydantic-settings, xrpl-py]
